# This file runs a local MCP server, providing the functions defined here to the agent. To use, configure your 
# environment to launch the MCP server, for example by adding the following the MCP.json:
# "r-tools": {
#   "command": "Rscript",
#   "args": [
#     "--vanilla",
#     "tools/server.R"
#   ]
# }

library(ellmer)
library(mcptools)
library(dplyr)
library(httr)
library(jsonlite)

.vectorSearch <- function(term, domain, limit = 1, maxRetries = 3, waitTime = 2) {
  params <- list(
    q = term,
    limit = limit
  )
  if (!is.null(domain)) {
    params$domain_id <- domain
  }
  url <- "https://hecate.pantheon-hds.com/api/search_standard"
  
  for (attempt in 1:maxRetries) {
    response <- tryCatch(
      {
        GET(url, query = params)
      },
      error = function(e) {
        message(paste("Attempt", attempt, "failed with error:", e$message))
        return(NULL)
      }
    )
    if (!is.null(response) && status_code(response) == 200) {
      content_text <- content(response, "text", encoding = "UTF-8")
      data <- fromJSON(content_text)
      data <- bind_rows(data$concepts) 
      return(data)
    }
    if (attempt < maxRetries) {
      message(sprintf(
        "Search failed for '%s' (Status: %s). Retrying in %s seconds...",
        term,
        if (is.null(response)) "Connection Error" else status_code(response),
        waitTime
      ))
      Sys.sleep(waitTime)
    }
  }
  stop(sprintf("All %s attempts failed for term '%s'.", maxRetries, term))
}


create_concept_set <- tool(
  function(name, definition = NULL, domain = NULL, variableName) {
    # Simple implementation for testing: use Hecate to find best matching concept, include all descendants
    concepts <- .vectorSearch(name, domain = domain)
    code <- sprintf("%s <- cs(descendants(%d), name = \"%s\")",
                    variableName,
                    concepts$concept_id,
                    name)
    # writeLines(code)
    return(code)
  },
  description = "Generate a concept set expression for a clinical idea. Outputs as Capr code.",
  arguments = list(
    name = type_string("The name of the idea for which to generate the concept set (e.g. 'Acute myocardial infarction')."),
    definition = type_string("(Optional) A definition of the idea", required = FALSE),
    domain = type_string("(Optional) The OMOP CDM domain to restrict to. (E.g. 'Condition' or 'Procedure')"),
    variableName = type_string("The name of the R variable to assign the Capr concept set to. Should be a valid name for an R variable (e.g. 'amiConceptSet')")
  )
)

evaluate_cohort <- tool(
  function(json) {
    # Dummy implementation:
    result <- list(
      list(
        database = "Merative Marketscan CCAE",
        description = "A large U.S. administrative dataset. It tracks healthcare use, costs, and prescriptions for active employees, early retirees, and their dependents with employer-sponsored insurance.",
        totalPopulation = 181000000000,
        cohortPopulation = 126241
      )
    )
  },
  description = "Evaluate a cohort against data in the OMOP CDM. Returns cohort sizes in one or more databases, with database metadata",
  arguments = list(
    json = type_string("Valid cohort JSON as generated by Capr.")
  )
  
)

# Start the MCP server -------------------------------------------------------------------------------------------------
# This will block the R session and listen for requests from Copilot/Claude.
mcp_server(
  tools = list(
    create_concept_set,
    evaluate_cohort
  ),
  session_tools = FALSE
)
